const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const express = require('express');
const { fileRepository, mongoRepository } = require('./repository');
const { keyFor } = require('./account-service');
const { registerAdminContentRoutes } = require('./admin-content-routes');
const { registerContentRoutes } = require('./content-routes');

test('CMS lifecycle, conflict handling, previews, media, and published snapshots', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'loomiq-cms-'));
  const previousMedia = process.env.MEDIA_STORAGE_PATH;
  process.env.MEDIA_STORAGE_PATH = path.join(dir, 'media');
  const repository = fileRepository(path.join(dir, 'state.json'));
  const token = 'a'.repeat(64);
  await repository.put('admins', 'test-admin', {email:'cms@example.invalid',roles:['superadmin']});
  await repository.put('sessions', keyFor(token), {adminKey:'test-admin',expiresAt:Date.now()+60000});
  const app = express(); app.use(express.json());
  registerAdminContentRoutes(app, {store:()=>repository,addAudit:async()=>{}});
  registerContentRoutes(app, {store:()=>repository});
  app.use((e,req,res,next)=>res.status(e.status || 500).json({message:e.message}));
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(async()=>{await new Promise(resolve=>server.close(resolve)); fs.rmSync(dir,{recursive:true,force:true}); if(previousMedia===undefined) delete process.env.MEDIA_STORAGE_PATH; else process.env.MEDIA_STORAGE_PATH=previousMedia;});
  const base = `http://127.0.0.1:${server.address().port}`;
  async function request(route, method='GET', body, authenticated=true) {
    const response = await fetch(base+route,{method,headers:{...(authenticated?{Cookie:`loomiq_admin_session=${token}`} : {}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
    return {status:response.status,body:await response.json()};
  }
  const pages='/api/admin/content/pages';
  const draft={id:'stable-id',title:'Original title',slug:'welcome',sections:[{id:'hero',type:'hero',props:{headline:'Hello'}},{id:'cta',type:'cta',props:{label:'Start now',link:'/signup',linkText:'Create account',backgroundColor:'#123456'}}],seo:{title:'Original SEO'}};
  assert.equal((await request(pages,'GET',null,false)).status,401);
  assert.equal((await request(pages,'POST',draft)).status,201);
  assert.equal((await request(pages,'POST',{...draft,id:'another'})).status,409);
  let detail=(await request(pages+'/stable-id')).body;
  assert.equal(detail.id,'stable-id');
  assert.equal((await request(pages+'/stable-id','PATCH',{sections:[{type:'features',props:{items:'bad'}}]})).status,400);
  assert.equal((await request(pages+'/stable-id','PATCH',{title:'Stale',lastModifiedAt:0})).status,409);
  const preview=(await request('/api/admin/content/preview-token','POST',{pageId:'stable-id'})).body;
  for(let i=0;i<2;i++) assert.equal((await request('/api/admin/content/preview/'+preview.token)).body.payload.title,'Original title');
  await request(pages+'/stable-id/publish','POST',{});
  assert.equal((await request('/api/content/pages/welcome')).body.title,'Original title');
  assert.equal((await request('/api/content/pages/welcome')).body.sections[1].props.linkText,'Create account');
  const first=(await request(pages+'/stable-id')).body.publishedVersionId;
  assert.equal((await request(pages+'/stable-id','PATCH',{title:'Draft title',seo:{title:'Draft SEO'}})).status,200);
  assert.equal((await request('/api/content/pages/welcome')).body.title,'Original title');
  assert.equal((await request('/api/content/pages/welcome')).body.seo.title,'Original SEO');
  await request(pages+'/stable-id/publish','POST',{});
  assert.equal((await request('/api/content/pages/welcome')).body.title,'Draft title');
  assert.equal((await request(pages+'/stable-id/versions/'+first+'/rollback','POST',{})).status,200);
  assert.equal((await request('/api/content/pages/welcome')).body.title,'Original title');
  await request(pages+'/stable-id/unpublish','POST',{status:'draft'});
  assert.equal((await request('/api/content/pages/welcome')).status,404);
  assert.equal((await request(pages+'/stable-id/unpublish','POST',{status:'archived'})).status,200);
  assert.equal((await request(pages+'/stable-id/publish','POST',{})).status,400);
  await request(pages+'/stable-id/unpublish','POST',{status:'draft'});
  await request(pages+'/stable-id','PATCH',{slug:'renamed'});
  await request(pages+'/stable-id/publish','POST',{});
  await request(pages+'/stable-id','PATCH',{slug:'unreleased-slug'});
  assert.equal((await request('/api/content/pages/renamed')).status,200);
  assert.equal((await request('/api/content/pages/unreleased-slug')).status,404);
  assert.equal((await request('/api/content/pages/welcome')).status,404);
  const form = new FormData();form.append('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'sample.png');
  assert.equal((await fetch(base+'/api/admin/content/media',{method:'POST',body:form})).status,401);
  assert.equal(fs.readdirSync(path.join(dir,'media')).length,0);
  const upload=await fetch(base+'/api/admin/content/media',{method:'POST',headers:{Cookie:`loomiq_admin_session=${token}`},body:form});
  assert.equal(upload.status,201);const media=await upload.json();
  const file=await fetch(base+media.url);assert.equal(file.status,200);assert.match(file.headers.get('content-type'),/image\/png/);
  assert.equal((await request('/api/admin/content/media/'+media.id,'PATCH',{altText:'A sample'})).status,200);
  assert.equal((await request('/api/admin/content/media')).body.items[0].filename,'sample.png');
  assert.equal((await request('/api/admin/content/media/'+media.id,'DELETE')).status,200);
  assert.equal((await request('/api/admin/content/media')).body.items.length,0);
});

test('Mongo repository retains CMS identifiers without changing account records',async()=>{
  const db={collection:()=>({findOne:async()=>({_id:'page-id',title:'Page'}),find:(_,options)=>({toArray:async()=>options.projection? [{title:'Page'}]:[{_id:'page-id',title:'Page'}]})})};
  const repo=mongoRepository(db);
  assert.equal((await repo.get('pages','page-id'))._id,'page-id');
  assert.equal((await repo.list('media'))[0]._id,'page-id');
  assert.equal((await repo.get('customers','page-id'))._id,undefined);
});
