import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from '../../frontend/node_modules/playwright/index.mjs'
const require = createRequire(new URL('../../backend/package.json', import.meta.url))
const express = require('express')
const bcrypt = require('bcrypt')
const { fileRepository } = require('./repository')
const { keyFor } = require('./account-service')
const { registerAdminRoutes } = require('./admin-routes')
const { registerAdminContentRoutes } = require('./admin-content-routes')

test('admin browser: login, create, edit, preview, publish, media, mobile, logout', async t => {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cms-browser-'))
  process.env.MEDIA_STORAGE_PATH=path.join(dir,'media')
  const repo=fileRepository(path.join(dir,'state.json'))
  await repo.put('admins',keyFor('editor@example.invalid'),{email:'editor@example.invalid',passwordHash:await bcrypt.hash('test-password-only',4),roles:['superadmin']})
  const app=express(); app.use(express.json())
  registerAdminRoutes(app,{store:()=>repo,addAudit:async()=>{}})
  registerAdminContentRoutes(app,{store:()=>repo,addAudit:async()=>{}})
  require('./website-content').registerWebsiteContentRoutes(app,{store:()=>repo,addAudit:async()=>{},...require('./admin-content-routes')})
  require('./admin-records').registerAdminRecordRoutes(app,{store:()=>repo,addAudit:async()=>{}})
  require('./admin-commerce').registerAdminCommerce(app,{store:()=>repo,addAudit:async(a,tx)=>tx.put('audit_logs',String(Date.now()),{...a,createdAt:Date.now()}),razorpay:null})
  await repo.put('customers',keyFor('buyer@example.invalid'),{email:'buyer@example.invalid',name:'Test Buyer',company:'Test Company',registeredAt:Date.now()})
  await repo.put('orders','order_browser',{id:'order_browser',customerKey:keyFor('buyer@example.invalid'),plan:'Starter',amount:199000,status:'paid',createdAt:Date.now(),paidAt:Date.now(),testMode:false,billing:{email:'buyer@example.invalid',name:'Test Buyer'}})
  const publicApp=express();publicApp.use(express.json())
  require('./website-content').registerWebsiteContentRoutes(publicApp,{store:()=>repo,addAudit:async()=>{},...require('./admin-content-routes')})
  require('./content-routes').registerContentRoutes(publicApp,{store:()=>repo})
  publicApp.post('/api/offers/visit',(_,res)=>res.json({eligible:false,reason:'expired',serverNow:Date.now(),expiresAt:0,signedUp:false}))
  require('./web').registerWebsite(publicApp,fileURLToPath(new URL('../../frontend/dist',import.meta.url)),()=>repo)
  const publicServer=publicApp.listen(0,'127.0.0.1');await new Promise(resolve=>publicServer.once('listening',resolve))
  t.after(()=>new Promise(resolve=>publicServer.close(resolve)))
  const dist=fileURLToPath(new URL('../dist',import.meta.url))
  app.use(express.static(dist))
  app.get(/^(?!\/api\/).*/,(_,res)=>res.sendFile(path.join(dist,'index.html')))
  app.use((err,req,res,next)=>res.status(err.status||500).json({message:err.message}))
  const server=app.listen(0,'127.0.0.1'); await new Promise(resolve=>server.once('listening',resolve))
  const browser=await chromium.launch()
  t.after(async()=>{await browser.close();await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true})})
  const page=await browser.newPage({viewport:{width:1440,height:1000}})
  const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.message)})
  page.on('console',msg=>{if(msg.type()==='error' && /React Router|TypeError|ReferenceError/.test(msg.text()))errors.push(msg.text())})
  page.setDefaultTimeout(10000)
  t.after(async()=>{if(!page.isClosed()) console.log('Final browser URL:',page.url())})
  const base=`http://127.0.0.1:${server.address().port}`
  await page.goto(base)
  await page.getByLabel('Email').fill('editor@example.invalid')
  await page.getByLabel('Password').fill('test-password-only')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await page.getByRole('heading',{name:'Content overview'}).waitFor()
  await page.getByRole('link',{name:'Customers',exact:true}).click()
  await page.getByRole('button',{name:'Manage customer'}).click()
  await page.getByRole('heading',{name:'Customer-specific pricing'}).waitFor()
  await page.getByLabel('Customer amount (INR)').fill('800.50')
  await page.getByLabel('Reason for change').fill('Browser test agreed rate')
  await page.getByRole('button',{name:'Save customer price',exact:true}).click()
  await page.getByText('Customer pricing saved. Future orders use the updated price.').waitFor()
  assert.equal((await repo.get('customers',keyFor('buyer@example.invalid'))).pricingOverrides.Starter.amount,80050)
  assert.equal((await repo.get('orders','order_browser')).amount,199000)
  await page.getByRole('link',{name:'Razorpay analytics',exact:true}).click()
  await page.getByRole('heading',{name:'Captured revenue by order date'}).waitFor()
  await page.getByRole('link',{name:'Test Buyer',exact:true}).waitFor()
  await page.getByRole('link',{name:'Custom pages',exact:true}).click()
  await page.getByRole('button',{name:'+ New page',exact:true}).click()
  await page.getByLabel('Page title',{exact:true}).fill('Browser test page')
  await page.getByLabel('URL slug',{exact:true}).fill('browser-test')
  await page.getByRole('button',{name:'Create draft'}).click()
  await page.getByRole('heading',{name:'Browser test page',exact:true}).waitFor()
  await page.getByRole('button',{name:'+ hero',exact:true}).click()
  await page.locator('.section-editor-cells input').first().fill('Preview works')
  await page.frameLocator('iframe').getByRole('heading',{name:'Preview works'}).waitFor()
  await page.getByRole('button',{name:'Publish page',exact:true}).click()
  await page.getByRole('status').filter({hasText:'Page published with your latest changes.'}).waitFor()
  const saved=(await repo.list('pages'))[0]
  assert.equal(saved.status,'published')
  assert.equal(saved.sections[0].props.headline,'Preview works')
  await page.getByLabel('Page title',{exact:true}).fill('Updated page')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  assert.equal(await page.getByLabel('Page title',{exact:true}).inputValue(),'Updated page')
  await page.getByRole('button',{name:'Save changes',exact:true}).click()
  await page.getByRole('status').filter({hasText:'Changes saved.'}).waitFor()
  await page.getByRole('button',{name:'Publish updates'}).click()
  await page.getByRole('status').filter({hasText:'Page published'}).waitFor()
  await page.frameLocator('iframe').getByRole('heading',{name:'Preview works'}).waitFor()
  await page.screenshot({path:'/tmp/loomiq-cms-editor.png',fullPage:true})
  await page.getByRole('link',{name:'Media library',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=','base64')})
  await page.getByRole('status').filter({hasText:'Upload complete.'}).waitFor()
  await page.locator('.asset-card').first().click()
  await page.getByLabel('Alternative text').fill('Test asset description')
  await page.getByRole('button',{name:'Save alt text'}).click()
  await page.getByRole('status').filter({hasText:'Alternative text saved.'}).waitFor()
  assert.equal((await repo.list('media'))[0].altText,'Test asset description')
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  await page.locator('.recent-row').first().waitFor()
  await page.screenshot({path:'/tmp/loomiq-cms-overview.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true)
  await page.screenshot({path:'/tmp/loomiq-cms-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('link',{name:'Website content',exact:true}).click()
  await page.getByRole('heading',{name:'Manage your entire website'}).waitFor().catch(async e=>{console.log('Body:',await page.locator('body').innerText());throw e})
  await page.locator('.content-groups').waitFor().catch(async e=>{console.log(await page.locator('body').innerText());throw e})
  await page.locator('.content-groups button').filter({hasText:/^Hero/}).first().click()
  const heroPanel=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Connected ERP software for orders, inventory, production, and finance.',exact:true})})
  await heroPanel.getByLabel('Value',{exact:true}).fill('Your entire website, managed in LoomIQ')
  await page.getByRole('button',{name:'Save draft',exact:true}).click()
  await page.getByRole('status').filter({hasText:'Draft saved.'}).waitFor()
  const publicPage=await browser.newPage()
  await publicPage.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort())
  const publicBase=`http://127.0.0.1:${publicServer.address().port}`
  await publicPage.goto(publicBase,{waitUntil:'domcontentloaded'})
  await publicPage.getByRole('heading',{name:'Connected ERP software for orders, inventory, production, and finance.',exact:true}).waitFor()
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'Publish website',exact:true}).click()
  await page.getByRole('status').filter({hasText:'Website published.'}).waitFor()
  await publicPage.reload({waitUntil:'domcontentloaded'})
  await publicPage.getByRole('heading',{name:'Your entire website, managed in LoomIQ',exact:true}).waitFor()
  for(const name of ['Site layout & checkout pricing','Info Page','Pricing','Payment Page','Footer','Features','seo']) {
    const button=page.locator('.content-groups button').filter({hasText:name}).first(); if(await button.count())await button.click()
  }
  await page.locator('.content-groups button').filter({hasText:/^Hero/}).first().click()
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:'/tmp/loomiq-website-cms.png',fullPage:true})
  await publicPage.screenshot({path:'/tmp/loomiq-managed-website.png',fullPage:true})
  const website=(await (await page.request.get(base+'/api/admin/website')).json())
  website.values['Site.pricing'].Starter={firstMonth:1050,recurring:2100}
  const draft=await page.request.put(base+'/api/admin/website',{data:{values:website.values,revision:website.revision}})
  assert.equal(draft.status(),200)
  const {revision}=await draft.json()
  assert.equal((await page.request.post(base+'/api/admin/website/publish',{data:{revision}})).status(),200)
  await publicPage.reload({waitUntil:'domcontentloaded'})
  await publicPage.locator('.pc-price').filter({hasText:'₹2,100'}).waitFor()
  await publicPage.goto(publicBase+'/browser-test',{waitUntil:'domcontentloaded'})
  await publicPage.getByRole('heading',{name:'Updated page',exact:true}).waitFor()
  await publicPage.getByRole('heading',{name:'Preview works',exact:true}).waitFor()
  assert.equal((await publicPage.request.get(publicBase+'/browser-test')).status(),200)
  await page.getByRole('link',{name:'Customer activity',exact:true}).click()
  await page.getByRole('heading',{name:'Customer activity',exact:true}).waitFor()
  await publicPage.close()
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  await page.getByRole('heading',{name:'Admin sign in'}).waitFor()
  assert.deepEqual(errors,[])
})
