import React from 'react'
import { useSearchParams } from 'react-router-dom'

type Activity={type:string;at:number;detail?:string}
type RecordData={id:string;name?:string;email?:string;company?:string;status?:string;createdAt?:number|string;plan?:string;amount?:number;notes?:string;expiresAt?:number|string;accountState?:string;activity?:Activity[];credentials?:{username?:string;loginUrl?:string;issuedAt?:number};onboarding?:{status:string;workspaceUrl?:string};erp?:{userId?:string};[key:string]:unknown}
const label=(value:string)=>value.replace(/_/g,' ')
const date=(value:unknown)=>{const time=typeof value==='number'?value:typeof value==='string'?Date.parse(value):NaN;return Number.isFinite(time)?new Date(time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}
const state=(item:RecordData,type:string)=>type==='customers'?item.accountState||item.onboarding?.status||'signed_up':item.status||'new'
function Timeline({item}:{item:RecordData}){const initial:Activity[]=[{type:'demo_requested',at:typeof item.createdAt==='number'?item.createdAt:Date.parse(String(item.createdAt)),detail:'Demo request submitted'}];const events=[...initial,...(item.activity||[])].filter(e=>Number.isFinite(e.at)).sort((a,b)=>b.at-a.at);return <div className="activity-timeline">{events.map((e,i)=><div key={`${e.type}-${e.at}-${i}`}><span className="activity-dot"/><div><strong>{label(e.type)}</strong><small>{date(e.at)}{e.detail?` · ${e.detail}`:''}</small></div></div>)}</div>}
export default function Records(){
  const [params,setParams]=useSearchParams(),type=params.get('type')||'enquiries',demo=type==='enquiries'
  const [search,setSearch]=React.useState(''),[page,setPage]=React.useState(1),[total,setTotal]=React.useState(0),[items,setItems]=React.useState<RecordData[]>([]),[selected,setSelected]=React.useState<RecordData|null>(null)
  const [statusValue,setStatusValue]=React.useState(''),[notes,setNotes]=React.useState(''),[url,setUrl]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[loading,setLoading]=React.useState(false),[refresh,setRefresh]=React.useState(0)
  React.useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>{fetch(`/api/admin/records/${type}?search=${encodeURIComponent(search)}&page=${page}`,{credentials:'include'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);if(active){setItems(d.items);setTotal(d.total);setError('')}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false))},200);return()=>{active=false;clearTimeout(timer)}},[type,search,page,refresh])
  async function save(){if(!selected)return;setBusy(true);try{const r=await fetch(`/api/admin/records/${type}/${encodeURIComponent(selected.id)}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:statusValue,notes,workspaceUrl:url})}),d=await r.json();if(!r.ok)throw new Error(d.message);setSelected(null);setRefresh(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="admin-shell"><h1>Customer activity</h1><p className="sub">See account sign-ups, verified demo access, ERP usage events, and paid conversion status.</p><div className="toolbar">{[['enquiries','Demo activity'],['customers','Accounts'],['orders','Orders'],['support','Support']].map(([v,title])=><button className="btn-ghost" disabled={type===v} key={v} onClick={()=>{setParams({type:v});setPage(1);setSelected(null)}}>{title}</button>)}<span className="spacer"/><input aria-label="Search records" placeholder="Search records…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{error&&<div className="error" role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>Retry</button></div>}{loading&&<p role="status">Loading records…</p>}
  <div className="panel table-wrap"><table className="cms"><thead><tr><th>{type==='orders'?'Plan':'Name'}</th><th>{type==='orders'?'Amount':'Email'}</th><th>{demo?'Access state':'Status'}</th><th>{demo?'Latest activity':'Created'}</th><th>Details</th></tr></thead><tbody>{items.map((item,i)=>{const latest=item.activity?.at(-1);return <tr key={String(item.id||i)}><td>{item.name||item.plan||'—'}</td><td>{type==='orders'?`₹${((item.amount||0)/100).toLocaleString('en-IN')}`:item.email}</td><td><span className="status-pill">{label(state(item,type))}</span></td><td>{demo&&latest?`${label(latest.type)} · ${date(latest.at)}`:date(item.createdAt)}</td><td><button className="btn-ghost" onClick={()=>{setSelected(item);setStatusValue(state(item,type));setNotes(String(item.notes||''));setUrl(item.onboarding?.workspaceUrl||'')}}>View</button></td></tr>})}</tbody></table>{!loading&&!items.length&&<p className="empty">No records found.</p>}</div>
  <div className="pagination"><button disabled={page===1||loading} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page} · {total} records</span><button disabled={page*20>=total||loading} onClick={()=>setPage(n=>n+1)}>Next</button></div>
  {selected&&<section className="panel record-panel"><div className="page-heading"><div><h2>{selected.name||selected.email||selected.id}</h2><p className="sub">{selected.company||selected.email}</p></div><button className="btn-ghost" onClick={()=>setSelected(null)}>Close</button></div>{demo?<><div className="activity-summary"><div><small>Demo status</small><strong>{label(state(selected,type))}</strong></div><div><small>Access expires</small><strong>{date(selected.expiresAt)}</strong></div><div><small>ERP identity</small><strong>{selected.erp?.userId||'Not created'}</strong></div></div><div className="record-grid"><section><h3>Activity timeline</h3><Timeline item={selected}/></section><section><h3>Demo credentials</h3>{selected.credentials?.username?<dl className="record-details"><dt>Username</dt><dd>{selected.credentials.username}</dd><dt>Login portal</dt><dd>{selected.credentials.loginUrl?<a href={selected.credentials.loginUrl} target="_blank" rel="noreferrer">Open ERP login</a>:'—'}</dd><dt>Temporary password</dt><dd>Not stored for security. Ask the user to reset it if needed.</dd><dt>Issued</dt><dd>{date(selected.credentials.issuedAt)}</dd></dl>:<p className="muted">Credentials are available only after email verification activates the demo.</p>}</section></div></>:<dl className="record-details">{Object.entries(selected).filter(([k,v])=>!['activity','credentials','erp','onboarding'].includes(k)&&v!==null&&v!==undefined).map(([k,v])=><React.Fragment key={k}><dt>{label(k)}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></React.Fragment>)}</dl>}{type!=='orders'&&!demo&&<><label>Status<select value={statusValue} onChange={e=>setStatusValue(e.target.value)}>{(type==='customers'?['requested','in-progress','active']:['new','in-progress','resolved','closed']).map(v=><option key={v}>{v}</option>)}</select></label>{type==='customers'?<label>Provisioned workspace URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://workspace.example.com"/></label>:<label>Internal notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>}<button disabled={busy} onClick={save}>{busy?'Saving…':'Save record'}</button></>}</section>}</div>
}
