import React from 'react'
import { useSearchParams } from 'react-router-dom'
type RecordData = {id:string;name?:string;email?:string;company?:string;status?:string;createdAt?:number;plan?:string;amount?:number;notes?:string;onboarding?:{status:string;workspaceUrl?:string};[key:string]:unknown}
export default function Records(){
  const [params,setParams]=useSearchParams()
  const type=params.get('type')||'enquiries'
  const [search,setSearch]=React.useState(''),[page,setPage]=React.useState(1),[total,setTotal]=React.useState(0)
  const [items,setItems]=React.useState<RecordData[]>([]),[selected,setSelected]=React.useState<RecordData|null>(null)
  const [status,setStatus]=React.useState(''),[notes,setNotes]=React.useState(''),[url,setUrl]=React.useState('')
  const [error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[loading,setLoading]=React.useState(false),[refresh,setRefresh]=React.useState(0)
  React.useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>{fetch(`/api/admin/records/${type}?search=${encodeURIComponent(search)}&page=${page}`,{credentials:'include'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.message);if(active){setItems(data.items);setTotal(data.total);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})},200);return()=>{active=false;clearTimeout(timer)}},[type,search,page,refresh])
  async function save(){if(!selected)return;setBusy(true);try{const response=await fetch(`/api/admin/records/${type}/${encodeURIComponent(selected.id)}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,notes,workspaceUrl:url})});const body=await response.json();if(!response.ok)throw new Error(body.message);setSelected(null);setRefresh(r=>r+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="admin-shell"><h1>Customer activity</h1><p className="sub">Manage enquiries, support requests, and onboarding. Orders show recorded payment data.</p><div className="toolbar">{['enquiries','customers','orders','support'].map(tab=><button className="btn-ghost" disabled={type===tab} key={tab} onClick={()=>{setParams({type:tab});setPage(1);setSelected(null)}}>{tab}</button>)}<span className="spacer"/><input aria-label="Search records" placeholder="Search records…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{error&&<div className="error" role="alert">{error}<button onClick={()=>setRefresh(r=>r+1)}>Retry</button></div>}{loading&&<p role="status">Loading records…</p>}
  <div className="panel table-wrap"><table className="cms"><thead><tr><th>{type==='orders'?'Plan':'Name'}</th><th>{type==='orders'?'Amount':'Email'}</th><th>Status</th><th>Created</th><th>Details</th></tr></thead><tbody>{items.map((item,i)=><tr key={String(item.id||i)}><td>{item.name||item.plan||'—'}</td><td>{type==='orders'?`₹${((item.amount||0)/100).toLocaleString('en-IN')}`:item.email}</td><td>{item.onboarding?.status||item.status||'—'}</td><td>{item.createdAt?new Date(item.createdAt).toLocaleDateString():'—'}</td><td><button className="btn-ghost" onClick={()=>{setSelected(item);setStatus(item.onboarding?.status||item.status||'new');setNotes(item.notes||'');setUrl(item.onboarding?.workspaceUrl||'')}}>View</button></td></tr>)}</tbody></table>{!loading&&!items.length&&<p className="empty">No records found.</p>}</div>
  <div className="pagination"><button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} · {total} records</span><button disabled={page*20>=total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  {selected&&<section className="panel"><div className="page-heading"><h2>Record details</h2><button className="btn-ghost" onClick={()=>setSelected(null)}>Close</button></div><dl className="record-details">{Object.entries(selected).filter(([,value])=>value!==null&&value!==undefined).map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value,null,2):String(value)}</dd></React.Fragment>)}</dl>{type!=='orders'&&<><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{(type==='customers'?['requested','in-progress','active']:['new','in-progress','resolved','closed']).map(value=><option key={value}>{value}</option>)}</select></label>{type==='customers'?<label>Provisioned workspace URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://workspace.example.com"/></label>:<label>Internal notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>}<button disabled={busy} onClick={save}>{busy?'Saving…':'Save record'}</button></>}</section>}
  </div>
}
