import React from 'react'
import { useBlocker } from 'react-router-dom'
import MediaManager from '../components/MediaManager'

type Value = string | number | boolean | Value[] | { [key: string]: Value }
type Field = {group: string;label: string;kind: string;default: Value;options?:string[]}
type Content = {catalog: Record<string, Field>;values: Record<string, Value>;revision: number;publishedAt: number|null;hasDraft: boolean;versions: {id:string;createdAt:number;createdBy:string}[]}
const labelFor = (name: string) => name.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/Section$/, '').replace(/^Site$/, 'Site layout & checkout pricing')
function emptyValue(value: Value): Value {
  if (typeof value === 'string') return ''
  if (typeof value === 'number') return 0
  if (typeof value === 'boolean') return false
  if (Array.isArray(value)) return []
  return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, emptyValue(child)]))
}
async function api(path = '', method = 'GET', body?: unknown) {
  const response = await fetch('/api/admin/website'+path,{method,credentials:'include',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)})
  const result=await response.json().catch(()=>({message:'Unable to connect to the server.'}))
  if(!response.ok) throw new Error(result.message||'Unable to update website content.')
  return result
}
function ValueEditor({value,example,onChange,name,depth=0}:{value:Value;example:Value;onChange:(value:Value)=>void;name:string;depth?:number}) {
  if(typeof value==='boolean') return <div><label className="content-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} />{labelFor(name)}</label><button type="button" className="btn-ghost" onClick={()=>onChange(emptyValue(value))}>Delete field</button></div>
  if(typeof value==='number') return <div><label>{labelFor(name)}<input type="number" min="0" step="0.01" value={value} onChange={e=>onChange(Number(e.target.value))} /></label><button type="button" className="btn-ghost" onClick={()=>onChange(emptyValue(value))}>Delete field</button></div>
  if(typeof value==='string') return <div><label>{labelFor(name)}{value.length>100 || /description|body|intro|text/i.test(name) ? <textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} /> : <input readOnly={name==='name'&&['Starter','Growth','Enterprise'].includes(value)} value={value} onChange={e=>onChange(e.target.value)} />}</label><button type="button" className="btn-ghost" disabled={name==='name'&&['Starter','Growth','Enterprise'].includes(value)} onClick={()=>onChange(emptyValue(value))}>Delete field</button></div>
  if(Array.isArray(value)) return <div className="content-list"><strong>{labelFor(name)} · {value.length} items</strong>{value.map((item,index)=><div className="content-list-item" key={index}><div className="toolbar"><strong>Item {index+1}</strong><span className="spacer"/><button type="button" className="btn-ghost" disabled={index===0||name==='plans'||name==='pricingPlans'} onClick={()=>{const next=[...value];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next)}}>↑</button><button type="button" className="btn-ghost" disabled={index===value.length-1||name==='plans'||name==='pricingPlans'} onClick={()=>{const next=[...value];[next[index+1],next[index]]=[next[index],next[index+1]];onChange(next)}}>↓</button><button type="button" className="btn-ghost" disabled={name==='plans'||name==='pricingPlans'} onClick={()=>onChange(value.filter((_,i)=>i!==index))}>Remove</button></div><ValueEditor name={typeof item==='string'?'Text':name} value={item} example={Array.isArray(example)?example[index]??example[0]:item} depth={depth+1} onChange={next=>onChange(value.map((item,i)=>i===index?next:item))}/></div>)}<button type="button" className="btn-ghost" disabled={name==='plans'||name==='pricingPlans'} onClick={()=>onChange([...value,structuredClone(Array.isArray(example)?example[0]??'':'')])}>+ Add item</button></div>
  return <div className={depth ? 'content-object' : ''}>{Object.entries(value).map(([key,child])=><ValueEditor key={key} name={key} value={child} example={typeof example==='object'&&!Array.isArray(example)?example[key]??child:child} depth={depth+1} onChange={next=>onChange({...value,[key]:next})}/>)}</div>
}
export default function WebsiteContent() {
  const [data,setData]=React.useState<Content|null>(null)
  const [saved,setSaved]=React.useState('')
  const [group,setGroup]=React.useState('Site')
  const [search,setSearch]=React.useState('')
  const [busy,setBusy]=React.useState(false)
  const [error,setError]=React.useState('')
  const [message,setMessage]=React.useState('')
  const dirty=!!data&&saved!==JSON.stringify(data.values)
  const blocker=useBlocker(dirty)
  React.useEffect(()=>{if(blocker.state==='blocked'){if(confirm('Discard unsaved website changes?'))blocker.proceed();else blocker.reset()}},[blocker])
  React.useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[dirty])
  async function load(){const next=await api();setData(next);setSaved(JSON.stringify(next.values))}
  React.useEffect(()=>{load().catch(e=>setError(e.message))},[])
  async function save(publish=false){if(!data)return;setBusy(true);setError('');setMessage('');try{const result=await api('','PUT',{values:data.values,revision:data.revision});if(publish)await api('/publish','POST',{revision:result.revision});await load();setMessage(publish?'Website published. Reload the public website to see your changes.':'Draft saved. The public website is unchanged until you publish.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function restore(id:string){if(!data||!confirm('Replace this draft with the selected version? Publish when ready to make it live.'))return;setBusy(true);try{await api('/restore/'+id,'POST',{revision:data.revision});await load();setMessage('Version restored to draft.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const groups=data?[...new Set(Object.values(data.catalog).map(item=>item.group))].sort():[]
  const fields=data?Object.entries(data.catalog).filter(([key,field])=>search?`${field.label} ${field.group} ${JSON.stringify(data.values[key])}`.toLowerCase().includes(search.toLowerCase()):field.group===group):[]
  return <div className="admin-shell"><div className="page-heading"><div><p className="eyebrow">WEBSITE CONTENT</p><h1>Manage your entire website</h1><p className="sub">Branding, homepage, navigation, forms, legal policies, checkout copy, and search metadata.</p></div><a className="primary-link" href={window.location.port==='5174'?`${window.location.protocol}//${window.location.hostname}:5173/`:'/'} target="_blank" rel="noreferrer">Open website ↗</a></div>
  {error&&<div className="error" role="alert">{error}<button className="btn-ghost" onClick={()=>{if(!dirty||confirm('Discard changes and reload?'))load().catch(e=>setError(e.message))}}>Reload</button></div>}{message&&<div className="success" role="status">{message}</div>}
  {!data?<p>Loading website content…</p>:<><div className="toolbar editor-toolbar"><span className={dirty?'unsaved':'muted'}>{dirty?'● Unsaved changes':data.hasDraft?'Saved draft · not published':'Up to date'}</span><small>{data.publishedAt?'Published '+new Date(data.publishedAt).toLocaleString():'Using original website content'}</small><span className="spacer"/><button disabled={busy||!dirty} onClick={()=>save()}>Save draft</button><button disabled={busy} onClick={()=>{if(confirm('Publish all saved and current website changes? Updated checkout prices apply to new orders.'))save(true)}}>{busy?'Working…':'Publish website'}</button></div>
  <div className="website-editor-layout"><aside className="panel content-groups"><input aria-label="Search website content" placeholder="Search all website content…" value={search} onChange={e=>setSearch(e.target.value)}/><p className="sub">{Object.keys(data.catalog).length} editable fields · {groups.length} groups</p>{groups.map(name=><button className={group===name&&!search?'active':''} key={name} onClick={()=>{setGroup(name);setSearch('')}}>{labelFor(name)}<small>{Object.values(data.catalog).filter(f=>f.group===name).length}</small></button>)}<h3>Published versions</h3>{data.versions.slice(0,12).map(version=><div className="version-row" key={version.id}><small>{new Date(version.createdAt).toLocaleString()}<br/>{version.createdBy}</small><button disabled={busy} className="btn-ghost" onClick={()=>restore(version.id)}>Restore draft</button></div>)}</aside>
  <fieldset disabled={busy} className="editor-fieldset"><h2>{search?'Search results':labelFor(group)}</h2>{group==='Site'&&!search&&<div className="panel"><p>Arrange the homepage below. Checkout prices are authoritative: they update the pricing cards, payment screen, and backend quotes together. Price placeholders such as {'{discount}'}, {'{starterOffer}'}, and {'{growthRegular}'} keep promotional wording synchronized. Keep these placeholders in your copy. Offer duration remains 24 hours.</p></div>}
  {!fields.length&&<div className="empty">No matching content.</div>}{fields.map(([key,field])=><section className="panel" key={key}><div className="page-heading"><div><small>{labelFor(field.group)}</small><h3>{field.label}</h3></div><button type="button" className="btn-ghost" onClick={()=>setData({...data,values:{...data.values,[key]:structuredClone(field.default)}})}>Reset field</button></div>{key==='Site.layout'?<div>{(data.values[key] as string[]).map((name,index)=><div className="toolbar" key={name}><strong>{index+1}. {labelFor(name)}</strong><span className="spacer"/><button className="btn-ghost" disabled={index===0} onClick={()=>{const next=[...(data.values[key] as string[])];[next[index-1],next[index]]=[next[index],next[index-1]];setData({...data,values:{...data.values,[key]:next}})}}>Move up</button><button className="btn-ghost" onClick={()=>setData({...data,values:{...data.values,[key]:(data.values[key] as string[]).filter((_,i)=>i!==index)}})}>Hide section</button></div>)}<label>Add a section<select value="" onChange={e=>{if(e.target.value)setData({...data,values:{...data.values,[key]:[...(data.values[key] as string[]),e.target.value]}})}}><option value="">Choose a section…</option>{field.options?.filter(name=>!(data.values[key] as string[]).includes(name)).map(name=><option value={name} key={name}>{labelFor(name)}</option>)}</select></label></div>:<ValueEditor name={field.kind==='structured'?field.label:'Value'} value={data.values[key]} example={field.default} onChange={value=>setData({...data,values:{...data.values,[key]:value}})}/>}{field.kind==='url'&&/image/i.test(field.label)&&<MediaManager value={String(data.values[key])} onChange={url=>setData({...data,values:{...data.values,[key]:url||field.default}})} label="Choose an image"/>}</section>)}</fieldset></div></>}
  </div>
}
