import "../InfoPage.css";
import logo from "../assets/company.logo.webp";
import SupportForm from '../components/SupportForm';

type InfoPageProps = { kind: "privacy" | "terms" | "refunds" };
const pages = {
  privacy: { title: "Privacy Policy", intro: "How LoomIQ uses account, payment, support and analytics information.", sections: [["Information we collect", "We collect the contact and company details you submit, account credentials, billing details, payment references, invoices and support messages. Razorpay handles card details; this website does not store them."], ["How we use information", "We use this information to authenticate accounts, process payments, provide invoices, guide onboarding, respond to support and refund requests, and protect the service."], ["Your requests", "Use the support form to request access, correction or deletion. We may retain information required for transactions or applicable recordkeeping."]] },
  terms: { title: "Terms of Service", intro: "Terms for LoomIQ accounts, monthly membership checkout and guided onboarding.", sections: [["Monthly membership", "Each checkout purchases one month of LoomIQ at the amount shown before payment. There are no automatic charges. Launch pricing is locked for the first three monthly purchases made within 90 days of the first paid purchase."], ["Access and onboarding", "Your LoomIQ account is created when you register. After payment, select your garment-production workflow and begin importing products, customers and stock with guided onboarding."], ["Support", "Demos are optional and intended for Enterprise or complex implementation requirements. Use the support form for help with your account, billing or setup."]] },
  refunds: { title: "Refund & Cancellation Policy", intro: "Our 7-day money-back guarantee and help with membership payments.", sections: [["7-Day Money-Back Guarantee", "Try LoomIQ with your actual business. If it is not right for you, request a refund within seven days of payment using the support form with your account email and order reference."], ["How refunds are handled", "We review eligible requests and return approved refunds to the original payment method through Razorpay. Processing time can vary by bank or payment provider."], ["No automatic renewal", "Each checkout is a one-time monthly payment. You do not need to cancel an automatic subscription."]] },
} as const;

export default function InfoPage({ kind }: InfoPageProps) {
  const page = pages[kind], base = import.meta.env.BASE_URL;
  return <div className="legal-page"><header className="legal-header"><a className="legal-brand" href={base}><img src={logo} alt="" width="32" height="32" /><span>LoomIQ</span></a><a className="legal-home" href={base}>Back to website ↗</a></header><main className="legal-main"><nav className="legal-breadcrumb" aria-label="Breadcrumb"><a href={base}>Home</a><span>/</span><span aria-current="page">{page.title}</span></nav><div className="legal-title"><p className="legal-eyebrow">LEGAL INFORMATION</p><h1>{page.title}</h1><p>{page.intro}</p></div><article className="legal-document" aria-label={page.title}>{page.sections.map(([heading, body], index) => <section key={heading} id={`section-${index + 1}`}><span className="legal-section-number">{String(index + 1).padStart(2, "0")}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}<div className="legal-document-contact"><h2>Contact LoomIQ</h2><p>Use the support form below with any questions.</p></div></article><SupportForm /></main><footer className="legal-footer"><span>© {new Date().getFullYear()} LoomIQ. All rights reserved.</span><nav><a href={base + "privacy"}>Privacy Policy</a><a href={base + "terms"}>Terms</a><a href={base + "refunds"}>Refund Policy</a></nav></footer></div>;
}
