import { useEffect,useState } from 'react'
import Header from './Header'
import FooterSection from './FooterSection'
import { cmsValue } from '../websiteContent'
type Page = {title:string;description:string;seo:Record<string,string>;sections:{id:string;type:string;props:Record<string,unknown>}[]}
const safeUrl=(value:unknown)=>typeof value==='string'&&!/^\s*(javascript|data|vbscript):/i.test(value)?value:'#'
export default function ManagedPage({slug}:{slug:string}){
  const [page,setPage]=useState<Page|null>(null),[error,setError]=useState('')
  useEffect(()=>{let active=true;fetch(`${import.meta.env.PUBLIC_API_URL??''}/api/content/pages/${encodeURIComponent(slug)}`).then(async r=>{if(!r.ok)throw new Error(r.status===404?'Page not found':'This page is temporarily unavailable.');const data=await r.json();if(active){setPage(data);document.title=data.seo?.title||data.title;const meta=document.querySelector('meta[name=description]');meta?.setAttribute('content',data.seo?.description||data.description||'');document.querySelector('meta[name=robots]')?.setAttribute('content',data.seo?.robots||'index, follow')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[slug])
  return <div className="app-shell"><Header/><main style={{maxWidth:1100,margin:'80px auto',padding:24}}>{error?<><h1>{error}</h1><a href={import.meta.env.BASE_URL}>{cmsValue('ManagedPage.1', 'Back to home')}</a></>:!page?<p>{cmsValue('ManagedPage.2', 'Loading pageâ€¦')}</p>:<><h1>{page.title}</h1><p>{page.description}</p>{page.sections.map(s=>{const p=s.props;const rows=(key:string)=>Array.isArray(p[key])?p[key] as Record<string,string>[]:[];return <section key={s.id} style={{padding:'32px 0'}}>{s.type==='hero'?<><h2>{String(p.headline||'')}</h2><p>{String(p.subheadline||'')}</p>{p.ctaText&&<a className="button button-primary" href={safeUrl(p.ctaLink)}>{String(p.ctaText)}</a>}</>:s.type==='richtext'?<p style={{whiteSpace:'pre-wrap'}}>{String(p.body||'')}</p>:s.type==='features'?rows('items').map((row,i)=><article key={i}><h3>{row.title}</h3><p>{row.description}</p></article>):s.type==='faq'?rows('items').map((row,i)=><details key={i}><summary>{row.question}</summary><p>{row.answer}</p></details>):s.type==='testimonials'?rows('entries').map((row,i)=><blockquote key={i}>{row.quote}<footer>{row.who}</footer></blockquote>):s.type==='cta'?<><h2>{String(p.label||'')}</h2><a className="button button-primary" href={safeUrl(p.link)}>{String(p.linkText||cmsValue('ManagedPage.3', 'Learn more'))}</a></>:null}</section>})}</>}</main><FooterSection/></div>
}
